### ISSUE TITLE
Create facade to access tracking records

### ISSUE THREAD

**Issue by unnawut** [maqe/laravel-qwatcher#9]
The package should be able to do the following:
- [ ] `QWatcher::all()` --> returns a collection
- [ ] `QWatcher::getById($id)` --> returns an object
- [ ] `QWatcher::getByStatus($status)` --> returns a collection
- [ ] `QWatcher::getByJobName($name)` --> returns a collection
